### ISSUE TITLE
Peer review web app from scratch 20/21 #week 1

### ISSUE THREAD

**Issue by ofahchouch-gh** [StanBankras/web-app-from-scratch-2021#1]
**# De code bevat geen syntaxfouten en is netjes opgemaakt**
De structuur is goed duidelijk en logisch opgezet. Code wordt ook in modules gezet.

Bij het maken van functies en variabelen wil je de intentie (intent) waarvoor je de variabel/functie gaat gebruiken weergeven en niet zo zeer wat er precies gebeurd in de variabel/functie. Dat doe jij ook redelijk goed. 

Verder wil je ook met abstractielagen werken in methods. Elke method bestaat uit maar 1 abstractielaag. Ook dat doe je goed.

**# JSON data kan met een asynchrone request worden opgehaald uit een API**
Het is je gelukt om data asynchroon met async/await op te halen uit de API.

**# JSON data kan, al dan niet met een micro library, client side in de HTML worden gerenderd.**
Het is je gelukt om gebruik te maken van het renderen van client side code in de HTML zoals we zien bij de functie renderCoins. 
Het enigste wat nodig is zoals je weet is vormgeving. Maar dat wist je zelf ook :)!

Verder zie ik niet dat je jezelf aan het herhalen bent in je code (DRY principe) en je maakt goed gebruik van scopes.

**# Over de Readme**
Je readme ziet er prima uit voor week 1. Alle informatie die ik nodig heb kon ik er uit halen.

**Comment by standrd** [comment]
Bedankt voor de feedback! Ik ben blij te horen dat je alles kon vinden wat werd verwacht voor deze eerste opzet in mijn repository. De vormgeving heb je gelijk in, daar moet zeker aan gewerkt worden ;)
