### ISSUE TITLE
Peer review web-app-from-scratch-2021

### ISSUE THREAD

**Issue by ofahchouch-gh** [StanBankras/web-app-from-scratch-2021#10]
**Structure & code quality**

- Ziet er goed uit allemaal, goed bezig
- Is het beter om de script tags in je index.html in je head te zetten? Met defer had ik begrepen dat ze pas worden uitgevoerd nadat je body is ingeladen (van Joost geleerd).
- Waarom importeer je de router in de app.js en is de app.js verder leeg ;o? 
- Nice, je bent je views, applicatie logica en je models/domein logica aan het abstraheren. Dit zorgt voor een duidelijker overzicht.
- Misschien proberen om voortaan met classes te werken? 
- Modules zijn meestal components die bij elkaar horen (als ik kijk naar Angular & Vue). In theorie heeft elke component dan zijn eigen view, controller & model. Je ziet dat dit ook gebeurd in Angular of in Vue, alleen worden ze dan niet zo genoemd. MVC is niet de enige architectuur natuurlijk, tijdens deze minor wil ik atomic design leren. Is wat moderner, maar zal vast veel lijken op MVC.
- Verder eigenlijk niks op aan te merken. Je functies zijn kort en krachtig en duidelijk.

**Data fetching, manipulation & visualization**
- Ziet er goed uit
- Zelf probeer ik m'n klasse die over de API calls gaat zo kort mogelijk te houden door daar geen logica af te handelen. Misschien handig om die logica te verplaatsen naar je laag waar je de applicatie logica hebt staan?
- Goed dat je ook met cache werkt
- Was misschien leuk geweest als data "live" te zien was? 

**Handling states & routes**
- Je router ziet er clean uit. Zo te zien werkt die ook stukken beter dan die Routie.js waar de meeste van ons mee hebben gewerkt.
- Is het mooier om alle childnodes te verwijderen inplaats van innerHTML = '' te gebruiken?
- Nice, je hebt aan een error state gewerkt. Goed dat je daar de tijd voor hebt genomen.

Verder goed bezig. Happy programming :D!

**Comment by standrd** [comment]
Thanks voor de feedback!

- Ik heb de app.js wat anders ingedeeld, het zag er inderdaad raar uit met alleen die router import (wat overigens wel werkte)
- Ik heb mn scripts in de head gezet, en mn libs gedownload zodat dit niet van een andere server hoeft te komen
- Classes wil ik in de toekomst zeker in gaan duiken!
