### ISSUE TITLE
Readme.md API

### ISSUE THREAD

**Issue by Mokerstier** [StanBankras/web-app-from-scratch-2021#11]
Je had de vorige issue geclosed maar nu zie ik alsnog geen info over de rate limits.

https://api.coinpaprika.com/#section/Rate-limit

Terwijl de documentatie wel beschikt over de informatie ;)

**Je laat echt punten liggen als je het niet opneemt man, zet het er gewoon in.**

P.S.
Ik doe dit niet om te bitchen hoor wil je gewoon helpen.

P.P.S.
Voor de rest ziet je `Readme.md` er goed uit !

**Comment by standrd** [comment]
Goed dat je hier nog op terugkomt, ik heb daar inderdaad helemaal niet aan gedacht! 
Bedankt voor het compliment over de readme :+1:
