### ISSUE TITLE
Peer review - Coins

### ISSUE THREAD

**Issue by Mokerstier** [StanBankras/web-app-from-scratch-2021#2]
https://github.com/StanBankras/web-app-from-scratch-2021/blob/43c89ebf1968313c60c2c2d5acd3d2b9e01dcf4b/js/coinpaprika.js#L3-L12

Je wilt globale variabelen zo veel mogelijk voorkomen:
```
let coins = [];
```

Kun je de getAllCoins() niet beter aan roepen vanuit je app en het resultaat opslaan in een variabele
wanneer je dan de coins weer nodig hebt in een andere functie kun je die weer meegeven:

```
export async function getTopCoins(until) { //<- hier dan weer die coins mee geven
  if(coins.length === 0) await getAllCoins(); // <- dan hoef je hier niet weer opnieuw te fetchen
// als hier coins.length === 0 dan kun je de bijvoorbeeld een error returnen
  return coins
    .sort((a, b) => {
      if(a.rank === 0) return 1;
      if(b.rank === 0) return -1;
      return b.rank < a.rank ? 1 : -1;
    })
    .slice(0, until);
}
```

**Comment by standrd** [comment]
Het werkt eigenlijk al op die manier, of ik begrijp het verkeerd. Na de eerste keer dat `getAllCoins()` is aangeroepen, worden ze opgeslagen in `let coins`. In de `getTopCoins` functie kijk ik of er al coins in die array staan: als die er staan wordt die call naar `getAllCoins` overgeslagen en wordt het direct uit de `let coins` gepakt, die global gedefined staat.

Wat ik me nu wel bedenk is dat nu inderdaad de `coins` alleen in deze module staan en niet toegankelijk zijn in de `app.js`. Ik vraag me alleen af of ik de coins buiten deze module nodig ga hebben, maar hier kan ik dus nog wel over nadenken. Thanks voor de feedback!

**Comment by standrd** [comment]
Ik heb hier nu een andere functie opgebouwd, ik sla wel nog steeds de coins op in een variable, maar die is gescoped aan 1 module, waar het ook alleen gebruikt gaat worden.
