### ISSUE TITLE
Peer feedback Minor

### ISSUE THREAD

**Issue by InjuMichorius** [StanBankras/web-app-from-scratch-2021#3]
Hi Stan 👋
Ik heb je repo nagekeken en de volgende punten gevonden.
- Je mist nog een descriptie van je repo aan de bovenkant die uitlegt waar het project over gaat
- De readme kan vollediger (daar ben je zo te zien nog mee bezig), maar de API en het concept zijn kort en helder uitgelegd.
- Je code ziet er clean uit en je maakt nu al gebruik van modules. Netjes!
- De loading state kan nog wat spice gebruiken, maar goed dat je er überhaupt al over na hebt gedacht!
- Het enige wat nog stappen kan maken is de vormgeving, maar daar heb je nog genoeg tijd voor 👍

**Comment by standrd** [comment]
Hi Inju, bedankt voor de feedback!

* Ik ga een goede beschrijving maken van waar het project over gaat, zeker belangrijk
* De README zal altijd een work in progress zijn tot het af is, maar daar heb je gelijk in: hij is nog een beetje kaal
