### ISSUE TITLE
Peer review week 2

### ISSUE THREAD

**Issue by johancvb** [StanBankras/web-app-from-scratch-2021#5]
Yoo! Je app ziet er goed uit man.

### **Repository**
Is there a link to the live demo at the top?
- Ja!

Is the concept described well in the readme?
- Ja, het concept wordt duidelijk uitgelegd. Het is een app die de upcoming events en 
meest recente tweets over cryptocurrencies laat zien.

Is the API described in the readme?
- Ja, namelijk de Coinpaprika API.

Are the Actor and Interaction diagrams included?
- Ja, die staan netjes in de readme.

### **Code**

**Actor diagram**
Do the actors make sense to you?
- De actors zijn duidelijk en ook logisch.

Do you see any function you wouldn't expect for a certain Actor?
- Nee, de actors zijn allemaal duidelijk en overzichtelijk in het diagram gezet.

**Interaction diagram**
Does the flow make sense to you?
- Opzich wel, alleen snap ik niet waarom er geen uitgaande pijl is bij het element "Data".

Does anything work differently than you would code it?
- Nee, alleen het "Data element". Het is niet echt duidelijk hoe deze wordt aangeroepen. Zit geen duidelijke flow in.

Click through the live demo

Does it work the way you would expect it to?
- Ja zeker! Hele goeie en strakke app. De routing werkt ook goed, styling ziet er goed uit. Heel vet!

What features or improvements would you like to see?
- Misschien nog een filter implementeren met de verschillende Cryptocurrencies? Zodat je snel de cryptomunt kan aanklikken en de bijbehorende tweets kan zien.

BROWSE the code
Has it already been structured according to the diagrams?
- Ja!

Check the code for consistency, is code being written the same way in different places?
- De code ziet er heel strak uit, consistent en overzichtelijk. Ook fijn dat er meerdere js files zijn met daarin verschillende functies. Dit zorgt voor meer overzicht in de codes.

Does the code follow naming conventions? Do variable and function names make sense to you?
- Ja, de variabelen zijn compact en duidelijk.

Blijf zo doorgaan man, je app ziet er super nice uit! :)

--Johan

**Comment by standrd** [comment]
Bedankt voor de feedback Johan!

Goed punt over dat data element, hij is inderdaad niet gelijk duidelijk zo op het eerste oog. Het idee van een filter/coin selecteren is erg goed en moet wel mogelijk zijn, aangezien ik toch alle coins al in laad! Thanks.
