### ISSUE TITLE
Peer review web-app-from-scratch-2021 actor & interaction diagram

### ISSUE THREAD

**Issue by ofahchouch-gh** [StanBankras/web-app-from-scratch-2021#6]
**Over actor & interaction diagram**
- Ziet er op eerste gezicht prima uit
- Je hebt vooral de applicatie logica beschreven, is het handig om ook de domein logica te beschrijven? Ik zie nergens een entiteit staan? Je zou bijvoorbeeld de entiteit/class CryptoCurrency kunnen gebruiken waar je alle gerelateerde methods van een CryptoCurrency in stopt zoals fetchTicker() die weer de fetchTicker aanroept in je entiteit/class API (of CoinPaprikaApiHandler). 
- Je kan zelfs nog verder gaan door CryptoCurrency in 3e te delen, om zo de MVC architectuur te proberen te gebruiken. CryptoCurrency kan een class hebben voor zijn View waar alle HTML/CSS gerelateerde zaken in gaan, een CryptoCurrencyController kan gaan over alle applicatie logica en CryptoCurrencyModel kan de attributen bevaten die je in de html renderd door gebruik te maken van getters en setters en ook kan je domein logica voor de entiteit CryptoCurrency hier dan in. Zo kan je straks je data makkelijker live updaten namelijk, wanneer dus een model een view update.
- Het interactie diagram ziet er prima uit en is logisch goed te volgen, als je MVC zou toepassen zou het er natuurlijk anders uit zien.

MVC is niet de enige architectuur die wordt gebruikt, maar wel 1 van de meest gebruikte voor bij het maken van web apps. Dus het is geen wet, maar 1 van "de" oplossingen.

**Comment by standrd** [comment]
Bedankt voor de zeer uitgebreide feedback, hier heb ik echt veel aan!

Ik ben bang dat het voor mij tijdens dit project te veel tijd gaat kosten om met classes te (leren) werken, maar ik ga me er zeker nog in verdiepen. Als ik tijd over heb kan ik het wellicht nog omzetten naar zo'n soort structuur.

**Comment by ofahchouch-gh** [comment]
Yeah, het is eigenlijk ook een beetje overkill en tijdrovend om MVC voor z'n project te gebruiken.

Happy programming in iedere geval :)!
