### ISSUE TITLE
Extra module

### ISSUE THREAD

**Issue by Mokerstier** [StanBankras/web-app-from-scratch-2021#7]
https://github.com/StanBankras/web-app-from-scratch-2021/blob/2e72bed22959f842b4bc6f8b05eb38678cdf8336/src/modules/templating.js#L4-L11

Misschien een mooie om nog een aparte module te maken die HTML voor je schrijft met createElement?

**Comment by standrd** [comment]
Voor templating waar ik eventlisteners aan wil hangen gebruik ik createElement, maar omdat dit altijd hetzelfde formaat zal blijven, en ik het 20x aanroep, is de insertAdjacentHTML sneller (createElement kost iets meer tijd). Ik heb op basis van deze issue wel op andere plaatsen templating aangepast naar createElement!
