### ISSUE TITLE
LocalStorage

### ISSUE THREAD

**Issue by Mokerstier** [StanBankras/web-app-from-scratch-2021#8]
https://github.com/StanBankras/web-app-from-scratch-2021/blob/2e72bed22959f842b4bc6f8b05eb38678cdf8336/src/modules/templating.js#L4-L11

Ik zie dat je met localStorage werkt maar wat als deze niet beschikbaar is, dan werkt je hele applicatie niet meer.

Je zou een check kunnen schrijven die kijkt of de localstorage beschikbaar is.

**Comment by standrd** [comment]
In mijn cache.js module wordt dit in principe al gecheckt. Ik heb vandaag wel extra error handling toegevoegd die het dan ook aan de gebruiker zal weergeven.
